### ISSUE TITLE
Don't use numbers in class name

### ISSUE THREAD

**Issue by ali-7** [FACG6/portfolio-page#26]
https://github.com/FACG6/portfolio-page/blob/89abf23c786b14baacaeccec138d9e7c71e7843f/style.css#L17

https://github.com/FACG6/portfolio-page/blob/89abf23c786b14baacaeccec138d9e7c71e7843f/style.css#L280

https://github.com/FACG6/portfolio-page/blob/89abf23c786b14baacaeccec138d9e7c71e7843f/style.css#L285

don't use numbers in naming a class !

**Comment by aminalakhsham** [comment]
i'll take it in my mind 👍
