### ISSUE TITLE
form ACTION PHP ???!!! 

### ISSUE THREAD

**Issue by ali-7** [FACG6/portfolio-page#29]
https://github.com/FACG6/portfolio-page/blob/89abf23c786b14baacaeccec138d9e7c71e7843f/index.html#L130

FIRST, why you **copy and paste** from other places ???!!!!

SECOND, don't use or write code you don't understand !!!
 - `action` attribute need a back-end server to use it.  

THIRD, how the rest of the team merge this code without review?!

**not acceptable !!**

**Comment by AsalaKM** [comment]
**Don't** write anything that you don't have an idea about it.
Also, try to be honest with yourself

**Comment by engshorouq** [comment]
Unintentional error , put it because i usually but this action in my works

**Comment by ali-7** [comment]
@engshorouq  you aren't the person who added this code !! <every thing is shown in github>
anyway, 
to the team >>> just remove it (like u done), don't repeat this, and move on ...

**Comment by aminalakhsham** [comment]
we do it @ali-7 
done @AsalaKM
