### ISSUE TITLE
Good Job !

### ISSUE THREAD

**Issue by ali-7** [FACG6/portfolio-page#30]
For a first week project, you guys made good work in your project, except some issues here and there but it's fine for your first project.

 - nice website
 - good branch naming (only one slip)
 - 100% accessibility
 - good git flow

please continue your work, and take my issues to improve and better yourselves.

Good Job !

**Comment by aminalakhsham** [comment]
ty big boss 
for hard work and make a lot of issue 
this is what i need 💯 @ali-7
