### ISSUE TITLE
Copy code !!!?

### ISSUE THREAD

**Issue by AsalaKM** [FACG6/portfolio-page#33]
### Guys !
**If you copy code, you are wasting your time and learning nothing.**
Your index and css files is copied from `w3schools` as you can see [here](https://www.w3schools.com/howto/howto_css_flip_card.asp)
https://github.com/FACG6/portfolio-page/blob/89abf23c786b14baacaeccec138d9e7c71e7843f/index.html#L51-L53
https://github.com/FACG6/portfolio-page/blob/89abf23c786b14baacaeccec138d9e7c71e7843f/style.css#L159-L221

 ### what I want to say is  as a mentor of this week I feel disappointed.

I **advice** you to never copy something unless you have created it from scratch before, and are confident that you can create it again. Then you can save your time by copying it, and even then, you might encounter a lot of bugs.

**Comment by aminalakhsham** [comment]
so sorry
