### ISSUE TITLE
White spacce

### ISSUE THREAD

**Issue by AbdallahAmmar96** [FACG6/portfolio-page#37]
There is white space at the bottom of website in About Us, Our Team and Contact Us.
For Ex.

![screencapture-facg6-github-io-portfolio-page-2019-01-10-09_01_25](https://user-images.githubusercontent.com/42452940/50951584-6275c700-14b6-11e9-866c-0c1d6661ebcd.png)

**Comment by aminalakhsham** [comment]
done

**Comment by aminalakhsham** [comment]
do it
