### ISSUE TITLE
to many logos

### ISSUE THREAD

**Issue by ahmedisam99** [FACG6/portfolio-page#40]
As a user i decide which logo is your official

![screencapture-facg6-github-io-portfolio-page-2019-01-10-09_23_52](https://user-images.githubusercontent.com/35656148/50952586-81298d00-14b9-11e9-9f5f-2c39a8251a47.png)

**Comment by aminalakhsham** [comment]
i think the first is out logo
the second , it's about name of team ,,,,
like team working
